### ISSUE TITLE
Add LICENSE file

### ISSUE THREAD

**Issue by cramertj** [PistonDevelopers/color_quant#3]

**Comment by cramertj** [comment]
@bvssvni Would you be able to add the file? Ironically my employer doesn't allow me to contribute the LICENSE file to this repo because this repo doesn't have a LICENSE file.

**Comment by cramertj** [comment]
@bvssvni Thanks so much for the quick turnaround! can you push a new version to crates.io?

**Comment by bvssvni** [comment]
@cramertj Done

**Comment by cramertj** [comment]
Thanks so much!
